// <auto-generated />
using Euro.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euro.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Euro.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Tłumiki"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Uchwyty"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Uszczelki"
                        });
                });

            modelBuilder.Entity("Euro.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Uniwersalny tłumik przelotowy ze stali kwasoodpornej.\nDługość puszki tłumika - 400 mm\nSzerokość/wysokość puszki tłumika - 220/130 mm\nDługość końcówki - 250 mm\nŚrednica końcówki - 89 mm\nŚrednica rury dolotowej - 50, 60, 63,5 , 70, 76 mm\nProdukt dostępny również w wersji z przetłoczeniem wewnątrz przelotu poprawiającym tłumienie.",
                            ImageURL = "",
                            ListPrice = 750.0,
                            Name = "Uniwersalny tłumik epliptyczny E113",
                            Producent = "RM MOTORS",
                            SerialNumber = "E113"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Tłumik ze stali kwasoodpornej z wbudowaną przepustnicą\n\nTyp zaworu - Podciśnieniowy\nWysokość/szerokość puszki - 130x220 mm\nŚrednica dolotu - 63,5 / 76 mm",
                            ImageURL = "",
                            ListPrice = 1500.0,
                            Name = "Tłumik przelotowy z zaworem podciśnieniowym E400",
                            Producent = "RM MOTORS",
                            SerialNumber = "E400"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Tłumik ze stali kwasoodpornej z wbudowaną przepustnicą\n\nTyp zaworu - Elektryczny\nWysokość/szerokość tłumika - 130x220 mm\nDługość puszki - 350 mm\nDługość całkowita - 740 mm",
                            ImageURL = "",
                            ListPrice = 2933.0,
                            Name = "Poprzeczny tłumik przelotowy z zaworem elektrycznym E600",
                            Producent = "RM MOTORS",
                            SerialNumber = "E600"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Sportowy wieszak tłumika wydechu, wykonany z twardszej mieszanki gumy zapewnia pewne trzymanie ograniczając ruchy układu wydechowego. Dzięki idealnie dobranej twardości nie wpływa na komfort użytkowania pojazdu.\n\nŚrednica otworów: 11mm\nDługość całkowita: 73mm\nSzerokość: 47mm\nWysokość: 21mm",
                            ImageURL = "",
                            ListPrice = 10.0,
                            Name = "Wieszak wydechu tłumika Czerwony FigerSPEC",
                            Producent = "FigerSPEC",
                            SerialNumber = "FG-WS-RED"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Sportowy wieszak tłumika wydechu, wykonany z twardszej mieszanki gumy zapewnia pewne trzymanie ograniczając ruchy układu wydechowego. Dzięki idealnie dobranej twardości nie wpływa na komfort użytkowania pojazdu.\n\nŚrednica otworów: 11mm\nDługość całkowita: 108mm\nSzerokość: 44mm\nWysokość: 20mm",
                            ImageURL = "",
                            ListPrice = 13.99,
                            Name = "Wieszak wydechu tłumika XL Czerwony FigerSPEC",
                            Producent = "FigerSPEC",
                            SerialNumber = "FG-WSXL-RED"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Uszczelka rury wydechowej",
                            ImageURL = "",
                            ListPrice = 8.9900000000000002,
                            Name = "Uszczelka, rura wylotowa JP GROUP 1121101500",
                            Producent = "JP-Group Automotive",
                            SerialNumber = "1121101500 "
                        });
                });

            modelBuilder.Entity("Euro.Models.Product", b =>
                {
                    b.HasOne("Euro.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
